ads/urls.py
from django.urls import path
from ads import views

app_name='ads'
urlpatterns = [path('', views.AdListView.as_view(), name='all'),
               path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
               path('ad/create', views.AdCreateView.as_view(), name='create_ad'),
               path('ad/<int:pk>/update', views.AdUpdateView.as_view(), name='update_ad'),
               path('ad/<int:pk>/delete', views.AdDeleteView.as_view(), name='delete_ad'),
               path('ad/ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
               path('ad/<int:pk>/comment', views.CommentCreateView.as_view(), name='create_ad_comment'),
               path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='delete_ad_comment'),
               path('ad/<int:pk>/favorite', views.AddFavoriteView.as_view(), name="ad_favorite"),
               path('ad/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
            ]

myarts/urls.py
from django.urls import path
from myarts import views

app_name='myarts'
urlpatterns = [
    path('', views.ArticleListView.as_view(), name='main_view'),
    path('article/<int:pk>', views.ArticleDetailView.as_view(), name='article_details'),
    path('article/create', views.ArticleCreateView.as_view(), name='create_article'),
    path('article/<int:pk>/update', views.ArticleUpdateView.as_view(), name='update_article'),
    path('article/<int:pk/delete', views.ArticleDeleteView.as_view(), name='delete_article'),
    ]

paymentapi/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    path('ads/', include('ads.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

myarts/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MinLengthValidator

# Create your models here.
class Article(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Title must be greater than one character")]
        )
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

myarts/views.py
from django.urls import reverse_lazy
from myarts.models import Article
from myarts.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView


# Create your views here.
class ArticleListView(OwnerListView):
    model = Article

class ArticleDetailView(OwnerDetailView):
    model = Article

class ArticleCreateView(OwnerCreateView):
    model = Article
    fields = ['title', 'text']
    success_url = reverse_lazy('myarts:main_view')

class ArticleUpdateView(OwnerUpdateView):
    model = Article
    fields = ['title', 'text']
    success_url = reverse_lazy('myarts:main_view')

class ArticleDeleteView(OwnerDeleteView):
    model = Article
    success_url = reverse_lazy('myarts:main_view')

myarts/templates/myarts/article_form.html
{% extends 'base_bootstrap.html' %}


{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
</form>
{% endblock %}

myarts/templates/myarts/article_list.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <h1>Articles</h1>
    <p>
        {% if article_list %}
        <ul>
            {% for article in article_list %}
            <li>
                <a href="{% url 'myarts:article_details' %}">{{ article.title }}</a>
                {% if article.owner == user %}
                (<a href="{% url 'myarts:update_article' article.id %}">Update</a> |
                <a href="{% url 'myarts:delete_article' article.id %}">Delete</a>)
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>There are no articles in the database.</p>
        {% endif %}
    </p>
    <a href="{% url 'myarts:create_article' %}">Add an article</a> |
    {% if user.is_authenticated %}
    <a href="{% url 'logout' %}?next={% url 'myarts:main_view' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}?next={% url 'myarts:main_view' %}">Login</a>
    {% endif %}
{% endblock %}