ads/urls.py
from django.urls import path
from ads import views

app_name='ads'
urlpatterns = [path('', views.AdListView.as_view(), name='all'),
               path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
               path('ad/create', views.AdCreateView.as_view(), name='create_ad'),
               path('ad/<int:pk>/update', views.AdUpdateView.as_view(), name='update_ad'),
               path('ad/<int:pk>/delete', views.AdDeleteView.as_view(), name='delete_ad'),
               path('ad/ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
               path('ad/<int:pk>/comment', views.CommentCreateView.as_view(), name='create_ad_comment'),
               path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='delete_ad_comment'),
               path('ad/<int:pk>/favorite', views.AddFavoriteView.as_view(), name="ad_favorite"),
               path('ad/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
            ]

cats/urls.py
from django.urls import path
from cats import views

app_name = 'cats'
urlpatterns = [path('', views.CatList.as_view(), name='cat_list'),
               path('main/create/', views.CatCreate.as_view(), name='cat_create'),
               path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
               path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
               path('breeds/', views.BreedList.as_view(), name='breed_list'),
               path('breed/create/', views.BreedCreate.as_view(), name='create_breed'),
               path('breed/<int:pk>/update/', views.BreedUpdate.as_view(), name='update_breed'),
               path('breed/<int:pk>/delete/', views.BreedDelete.as_view(), name='delete_breed')]

paymentapi/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    path('ads/', include('ads.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

# Create your models here.
class Breed(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Breed must be greater than 1 character")]
        )

    def __str__(self):
        return self.name


class Cat(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
        )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

cats/forms.py
from django import forms
from cats.models import Cat

class CatForm(forms.ModelForm):
    class Meta:
        model = Cat
        fields = '__all__'

cats/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


from cats.models import Cat, Breed
from cats.forms import CatForm

# Create your views here.
class CatList(LoginRequiredMixin, View):
    template = 'cats/cat_list.html'
    def get(self, request):
        cl = Cat.objects.all()
        bc = Breed.objects.count()

        ctx = {'cat_list':cl, 'breed_count':bc}
        return render(request, self.template, ctx)

class CatCreate(LoginRequiredMixin, View):
    template = 'cats/cat_form.html'
    success_url = reverse_lazy('cats:cat_list')

    def get(self, request):
        form = CatForm()
        ctx = {'form':form}
        return render(request, self.template, ctx)

    def post(self, request):
        form = CatForm(request.POST)
        if not form.is_valid():
            ctx = {'form':form}
            return render(request, self.template, ctx)
        form.save()
        return redirect(self.success_url)

class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:cat_list')

class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:cat_list')

class BreedList(LoginRequiredMixin, View):
    template = 'cats/breed_list.html'
    def get(self, request):
        bl = Breed.objects.all()
        ctx = {'breed_list':bl}
        return render(request, self.template, ctx)

class BreedCreate(LoginRequiredMixin, CreateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:cat_list')

class BreedUpdate(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:breed_list')

class BreedDelete(LoginRequiredMixin, DeleteView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:breed_list')

cats/templates/cats/breed_confirm_delete.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <h1>Delete breed</h1>
    <p>Are you sure you want to delete the breed: {{ breed }}</p>

    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
        <input type="submit" onclick="window.location='{% url 'cats:cat_list' %}' ; return false;" value="Cancel">
    </form>
{% endblock %}

cats/templates/cats/breed_form.html
{% extends 'base_bootstrap.html' %}

{% block content %}
<form action='' method='post'>
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:cat_list' %}'" value="Cancel">
</form>
{% endblock %}

cats/templates/cats/breed_list.html
{% extends 'base_bootstrap.html' %}

{% block content %}
<h1>Breed List</h1>
<ul>
    {% for breed in breed_list %}
        <li>{{ breed.name }} (<a href="{% url 'cats:update_breed' breed.id %}">Update</a> | <a href="{% url 'cats:delete_breed' breed.id %}">Delete</a>)</li>
    {% endfor %}
</ul>
{% endblock %}

cats/templates/cats/cat_confirm_delete.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    <h1>Delete cat</h1>
    <p>Are you sure you want to delete the cat: {{ cat }}</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete">
        <input type="submit" onclick="window.location='{% url 'cats:cat_list' %}'" value="Cancel">
    </form>
{% endblock %}

cats/templates/cats/cat_form.html
{% extends 'base_bootstrap.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'cats:cat_list' %}'" value="Cancel">
</form>
{% endblock %}

cats/templates/cats/cat_list.html
{% extends 'base_bootstrap.html' %}

{% block content %}
    {% if cat_list %}
    <ul>
    {% for cat in cat_list %}
        <li>{{ cat.nickname }}(<a href="{% url 'cats:cat_update' cat.id %}">Update</a>|
                              <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>)</li>
    {% endfor %}
    </ul>
    {% else %}
    <p>There are no cats in the database.</p>
    {% endif %}

    {% if breed_count > 0 %}
    <p><a href="{% url 'cats:cat_create'%}">Add a cat</a></p>
    <a href="{% url 'cats:breed_list' %}">View breeds</a>
    {% else %}
    <p>There are no breeds. Please add a breed to add a Cat</p>
    {% endif %}
    <a href="{% url 'cats:create_breed' %}">Add a breed</a>

{% endblock %}